image: node:18

stages:
  - build

# 缓存 node_modules 以加速构建
cache:
  paths:
    - node_modules/

.build_template: &build_definition
  stage: build
  before_script:
    - npm install -g electron-builder electronize
    - npm install
  script:
    - electronize build /target $PLATFORM
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

build-windows:
  <<: *build_definition
  variables:
    PLATFORM: win
  tags:
    - windows

build-linux:
  <<: *build_definition
  variables:
    PLATFORM: linux
  tags:
    - linux

build-macos:
  <<: *build_definition
  variables:
    PLATFORM: mac
  tags:
    - macos
