using Microsoft.AspNetCore.Components.WebView;
using Microsoft.AspNetCore.Components.WebView.Maui;
using Microsoft.Extensions.FileProviders;
using Quantum.Infrastructure.Plugins;

namespace Quantum;

public sealed class PluginBlazorWebView : BlazorWebView
{
    private readonly PluginStaticAssetFileProvider _pluginAssets;

    public PluginBlazorWebView(PluginStaticAssetFileProvider pluginAssets)
    {
        _pluginAssets = pluginAssets;
        UrlLoading += OnUrlLoading;
    }

    public override IFileProvider CreateFileProvider(string contentRootDir)
        => new CompositeFileProvider(base.CreateFileProvider(contentRootDir), _pluginAssets);

    private static void OnUrlLoading(object? sender, UrlLoadingEventArgs eventArgs)
    {
        // MAUI treats non-host schemes as external by default. Plugin frame documents are
        // generated by the trusted parent as blob URLs and must remain inside the WebView.
        if (string.Equals(eventArgs.Url.Scheme, "blob", StringComparison.OrdinalIgnoreCase))
        {
            eventArgs.UrlLoadingStrategy = UrlLoadingStrategy.OpenInWebView;
        }
    }
}
