<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>quantum-extension-market</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Quantum.ExtensionMarket.Application\Quantum.ExtensionMarket.Application.csproj" />
    <ProjectReference Include="..\Quantum.ExtensionMarket.Contract\Quantum.ExtensionMarket.Contract.csproj" />
    <ProjectReference Include="..\Quantum.ExtensionMarket.Domain\Quantum.ExtensionMarket.Domain.csproj" />
    <ProjectReference Include="..\Quantum.ExtensionMarket.Infrastructure\Quantum.ExtensionMarket.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NOF.Hosting.AspNetCore" />
    <PackageReference Include="NOF.Hosting.AspNetCore.Extension.OidcServer" />
    <PackageReference Include="NOF.Infrastructure" />
    <PackageReference Include="NOF.Infrastructure.EntityFrameworkCore" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
</Project>
