name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  

env:
  DOTNET_VERSION: '9.0.x'    # .NET SDK 版本
  CONFIGURATION: 'Release'    # 构建配置

jobs:
  build:
    name: Build and Test
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: |
        dotnet restore ./Quantum.BuildTool/Quantum.BuildTool.csproj
        dotnet restore ./Quantum.Shell/Quantum.Shell.csproj
    
    - name: Build Quantum.BuildTool
      run: dotnet build ./Quantum.BuildTool/Quantum.BuildTool.csproj -c ${{ env.CONFIGURATION }} --no-restore /warnaserror
    
    - name: Build Quantum.Shell
      run: dotnet build ./Quantum.Shell/Quantum.Shell.csproj -c ${{ env.CONFIGURATION }} --no-restore /warnaserror
    
    - name: Test
      run: |
        dotnet test ./Quantum.BuildTool/Quantum.BuildTool.csproj -c ${{ env.CONFIGURATION }} --no-build --verbosity normal
        dotnet test ./Quantum.Shell/Quantum.Shell.csproj -c ${{ env.CONFIGURATION }} --no-build --verbosity normal
